/**
 * Canonical Hunter Missions — Weekly / Monthly / Elite.
 * missionKey is stable; titles may be updated on seed sync.
 */

const CATEGORIES = {
  Fitness: { icon: '🏋', color: 'fitness' },
  Health: { icon: '❤️', color: 'health' },
  Knowledge: { icon: '🧠', color: 'knowledge' },
  Professional: { icon: '💼', color: 'professional' },
  Elite: { icon: '⭐', color: 'elite' },
};

const TRACKING = {
  MANUAL: 'manual',
  WORKOUT: 'workout',
  STEPS: 'steps',
  CARDIO: 'cardio',
  STUDY_HOURS: 'study_hours',
  WATER: 'water',
  PROTEIN: 'protein',
  SLEEP: 'sleep',
  OVERLOAD: 'overload',
  ELITE_MONTHLY: 'elite_monthly',
};

const WEEKLY_MISSIONS = [
  {
    missionKey: 'w_fitness_workouts',
    title: 'Complete 5 Workout Sessions',
    description: 'Finish 5 lifting days from Daily Grind this week.',
    category: 'Fitness',
    targetCount: 5,
    expReward: 500,
    trackingSource: TRACKING.WORKOUT,
    unit: 'sessions',
    sortOrder: 10,
  },
  {
    missionKey: 'w_fitness_steps',
    title: 'Walk 40,000 Steps',
    description: 'Accumulate brisk steps across the week (recovery days count).',
    category: 'Fitness',
    targetCount: 40000,
    expReward: 350,
    trackingSource: TRACKING.STEPS,
    unit: 'steps',
    sortOrder: 20,
  },
  {
    missionKey: 'w_fitness_cardio',
    title: 'Complete 3 Cardio Sessions',
    description: 'Auto-tracked when workout or recovery cardio is cleared.',
    category: 'Fitness',
    targetCount: 3,
    expReward: 300,
    trackingSource: TRACKING.CARDIO,
    unit: 'sessions',
    sortOrder: 30,
  },
  {
    missionKey: 'w_health_water',
    title: 'Drink 21 Liters of Water',
    description: 'Hydration from Daily Grind water quests this week.',
    category: 'Health',
    targetCount: 21,
    expReward: 250,
    trackingSource: TRACKING.WATER,
    unit: 'L',
    sortOrder: 40,
  },
  {
    missionKey: 'w_health_protein',
    title: 'Eat 25 High-Protein Meals',
    description: 'Log protein-focused meals for recovery and growth.',
    category: 'Health',
    targetCount: 25,
    expReward: 350,
    trackingSource: TRACKING.PROTEIN,
    unit: 'meals',
    sortOrder: 50,
  },
  {
    missionKey: 'w_health_sleep',
    title: 'Sleep At Least 7 Hours For 6 Nights',
    description: 'Clear the sleep quest on 6 different nights this week.',
    category: 'Health',
    targetCount: 6,
    expReward: 350,
    trackingSource: TRACKING.SLEEP,
    unit: 'nights',
    sortOrder: 60,
  },
  {
    missionKey: 'w_knowledge_study',
    title: 'Study 5 Hours',
    description: 'Skill practice hours auto-tracked from Daily Grind.',
    category: 'Knowledge',
    targetCount: 5,
    expReward: 350,
    trackingSource: TRACKING.STUDY_HOURS,
    unit: 'hrs',
    sortOrder: 70,
  },
  {
    missionKey: 'w_knowledge_pages',
    title: 'Read 50 Pages',
    description: 'Track reading progress manually throughout the week.',
    category: 'Knowledge',
    targetCount: 50,
    expReward: 250,
    trackingSource: TRACKING.MANUAL,
    unit: 'pages',
    sortOrder: 80,
  },
  {
    missionKey: 'w_professional_career',
    title: 'Complete 3 Portfolio / Career Tasks',
    description: 'Ship features, push code, fix bugs, apply, deploy — your call.',
    category: 'Professional',
    targetCount: 3,
    expReward: 500,
    trackingSource: TRACKING.MANUAL,
    unit: 'tasks',
    sortOrder: 90,
  },
];

const MONTHLY_MISSIONS = [
  {
    missionKey: 'm_fitness_workouts',
    title: 'Complete 20 Workout Sessions',
    description: 'Twenty lifting sessions this month from Daily Grind.',
    category: 'Fitness',
    targetCount: 20,
    expReward: 2000,
    trackingSource: TRACKING.WORKOUT,
    unit: 'sessions',
    sortOrder: 10,
  },
  {
    missionKey: 'm_fitness_steps',
    title: 'Walk 180,000 Steps',
    description: 'Accumulate steps across the month.',
    category: 'Fitness',
    targetCount: 180000,
    expReward: 1500,
    trackingSource: TRACKING.STEPS,
    unit: 'steps',
    sortOrder: 20,
  },
  {
    missionKey: 'm_fitness_overload',
    title: 'Progress on 10 Exercises',
    description: 'Earn Progressive Overload upgrades on 10 different lifts.',
    category: 'Fitness',
    targetCount: 10,
    expReward: 2000,
    trackingSource: TRACKING.OVERLOAD,
    unit: 'lifts',
    sortOrder: 30,
  },
  {
    missionKey: 'm_health_water',
    title: 'Drink 90 Liters of Water',
    description: 'Monthly hydration total from Daily Grind.',
    category: 'Health',
    targetCount: 90,
    expReward: 800,
    trackingSource: TRACKING.WATER,
    unit: 'L',
    sortOrder: 40,
  },
  {
    missionKey: 'm_health_protein',
    title: 'Eat 100 High-Protein Meals',
    description: 'Keep protein high for the entire month.',
    category: 'Health',
    targetCount: 100,
    expReward: 1000,
    trackingSource: TRACKING.PROTEIN,
    unit: 'meals',
    sortOrder: 50,
  },
  {
    missionKey: 'm_health_sleep',
    title: 'Sleep At Least 7 Hours For 25 Nights',
    description: 'Clear sleep quest on 25 nights this month.',
    category: 'Health',
    targetCount: 25,
    expReward: 1200,
    trackingSource: TRACKING.SLEEP,
    unit: 'nights',
    sortOrder: 60,
  },
  {
    missionKey: 'm_knowledge_study',
    title: 'Study 20 Hours',
    description: 'Auto-tracked study / skill practice hours.',
    category: 'Knowledge',
    targetCount: 20,
    expReward: 1500,
    trackingSource: TRACKING.STUDY_HOURS,
    unit: 'hrs',
    sortOrder: 70,
  },
  {
    missionKey: 'm_knowledge_pages',
    title: 'Read 200 Pages',
    description: 'Manual reading progress for the month.',
    category: 'Knowledge',
    targetCount: 200,
    expReward: 800,
    trackingSource: TRACKING.MANUAL,
    unit: 'pages',
    sortOrder: 80,
  },
  {
    missionKey: 'm_professional_project',
    title: 'Complete One Major Project',
    description: 'Ship an app, deploy a site, finish a portfolio or course.',
    category: 'Professional',
    targetCount: 1,
    expReward: 2500,
    trackingSource: TRACKING.MANUAL,
    unit: 'project',
    sortOrder: 90,
  },
  {
    missionKey: 'm_elite_all_trials',
    title: 'Complete EVERY Monthly Hunter Trial',
    description: 'Clear all standard monthly trials to claim the Elite reward.',
    category: 'Elite',
    targetCount: 9, // non-elite monthly count
    expReward: 5000,
    trackingSource: TRACKING.ELITE_MONTHLY,
    unit: 'trials',
    sortOrder: 100,
    isElite: true,
    eliteStatBoost: 5,
    eliteBadgeId: 'elite_monthly_monarch',
  },
];

module.exports = {
  CATEGORIES,
  TRACKING,
  WEEKLY_MISSIONS,
  MONTHLY_MISSIONS,
};
